kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '8'
  name: laravel
  namespace: ahmed
  labels:
    layer: laravel
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      layer: laravel
      tier: backend
  template:
    metadata:
      labels:
        layer: laravel
        tier: backend
    spec:
      volumes:
        # Laravel Source Code Volume
        - name: laravel-app-pvc
          persistentVolumeClaim:
            claimName: laravel-pvc
        - name: app
          emptyDir:
      containers:
        # Laravel Containers
        - name: laravel
          ports:
            - containerPort: 9000
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: laravel-app-pvc
              mountPath: /app/storage
              subPath: storage
            - name: laravel-app-pvc
              mountPath: /app
          envFrom:
            - configMapRef:
                name: laravel-env
            - secretRef:
                name: laravel-env
          image: 'registry.i-3.my.id:5000/repository/docker-internal/ahmad/laravel:1.2'
      imagePullSecrets:
        - name: lab-nexus-ahmad
      initContainers:
      - name: install
        image: registry.i-3.my.id:5000/repository/docker-internal/ahmad/laravel:1.2
        volumeMounts:
        - name: laravel-app-pvc
          mountPath: /app
        command:
        - cp
        - "-r"
        - "/var/www/."
        - "/app"